# Generated by Django 3.1.1 on 2020-09-23 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unesco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='description',
            field=models.TextField(max_length=2000),
        ),
    ]
