# Generated by Django 3.1.1 on 2020-09-25 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_auto_20200925_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='ad',
            new_name='title',
        ),
    ]
