# Generated by Django 3.1.1 on 2020-09-26 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_auto_20200925_2346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='title',
            new_name='ad',
        ),
    ]
